### ISSUE TITLE
Test workflow utilizes a cache and doesn't work with the java app

### ISSUE THREAD

**Issue by Kwandes** [treecreate/webstore#25]
The test workflow utilizes NX Cloud and gets the test results from the cache instead of running them. This makes the tests give false positives.
The package.json should include a new test target, `test:ci`, that skips the cache during testing
```json
    "test:ci": "nx run-many --all --target=test --skip-nx-cache",
```

Once that is fixed, the java tests will also fail in the workflow due to not having the JDK actually installed.
This can be done by adding an extra setup check
```yaml
      # Setup JDK for java tests
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
```
