### ISSUE TITLE
Add a e2e CI workflow

### ISSUE THREAD

**Issue by Kwandes** [treecreate/webstore#51]
### Add a Github actions workflow that automatically executes the e2e tests

Once issue #43 is merged, the project will include e2e tests (`webstore-e2e`) as well as new scripts in the `package.json` meant specifically for running e2e tests

The workflow should utilise the `e2e:ci` script which executes the e2e tests for webstore-e2e in headless mode (no browser)

**Workflow name:** E2E CI
The workflow should execute on **pushes** and **pull requests**, as well as manual dispatch

#### Example workflow:
```yaml
# Continous Integration workflow for running end-to-end tests
name: E2E CI 

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install and run end-to-end tests
        # Install the apps using npm ci (ensures a clean install)
        run: |
          npm ci
          npm run e2e:ci
```
